### ISSUE TITLE
When will release code & dataset ?

### ISSUE THREAD

**Issue by leo-frank** [fabiotosi92/NeRF-Supervised-Deep-Stereo#1]
THanks for your great work.

I wonder when will release code & dataset ? I am very excited to see your great work

**Comment by mattpoggi** [comment]
Hi @leo-frank,
Hold on, data will be ready for release by mid May.

**Comment by tellyoung** [comment]
What about the code? I'm also interested

**Comment by mattpoggi** [comment]
Sure, trained models and code snippets will be released close to the data release.

**Comment by javierliberman** [comment]
Hi! I'm also very interested in seeing your great work in code!

**Comment by xjcvip007** [comment]
@mattpoggi thanks for your amazing job, One question, the code is expected to be released this month, right?

**Comment by umie0128** [comment]
@mattpoggi  Hi i waiting for your great work

**Comment by mattpoggi** [comment]
Hi all,
because of some admin stuff (and ICCV rebuttals), we will have everything online in a couple of days.
Sorry about this, almost there :)

**Comment by fabiotosi92** [comment]
Hi all! We are pleased to inform you that we have released both the code snippets and the dataset for our research work. The code snippets can be found in the repository, and the dataset is available through the provided link. We appreciate your interest and hope you find the resources useful.
