### ISSUE TITLE
The baseline calculation of stereo camera

### ISSUE THREAD

**Issue by guangxuwang** [fabiotosi92/NeRF-Supervised-Deep-Stereo#10]
I have a question about the baseline calculation of generated stereo camera,  I don't know how to calculate it？

When the default shift is set to-0.2 in code generate_stereo_pair_matrix.py  , how can i get baseline ?

![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/104683713/c892a90e-7e2b-4591-bbaa-4f45858c8eb4)

**Comment by fabiotosi92** [comment]
Hello, the baseline value is completely arbitrary, meaning you have the freedom to select any value that suits your specific requirements.

**Comment by guangxuwang** [comment]
@fabiotosi92 How do I get a baseline according to the shift value?  For example，When the default shift is set to-0.2 in code generate_stereo_pair_matrix.py , how can i calculate the baseline value?

**Comment by fabiotosi92** [comment]
In this case, the shift represents the baseline.

**Comment by guangxuwang** [comment]
thank you ！



At 2023-07-05 19:46:56, "Fabio Tosi" ***@***.***> wrote:

In this case, the shift represents the baseline.
