### ISSUE TITLE
how generate center view on my stereo pairs scene ? 

### ISSUE THREAD

**Issue by 565ee** [fabiotosi92/NeRF-Supervised-Deep-Stereo#11]
thank your NeRF-Supervised-Deep-Stereo !! i like it very much !!

but now, i have a question : 
i have left.jpg  right.jpg  disp0.pfm  calib.txt
and use colmap generate  :  poses\colmap_sparse  colmap_text  colmap.db

i use : python test.py ... , generate  .../outdir/0.jpg  0.npy
i use : python demo.py ... , generate  .../outdir/disparity_map.png

now , how generate center view on my stereo pairs scene by baseline ?
what code?  what python packages? 
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/28084126/ff23c17a-9661-480f-872b-7bdd3fa90217)

**Comment by fabiotosi92** [comment]
Hi, are you trying to generate stereo pairs on your specific scene or are you using our dataset? In the latter case, you already have the center view for each rendered triplet. If you need more information, please refer to the documentation, which you can find at this [link](https://amsacta.unibo.it/id/eprint/7218/32/README_NeRF_stereo.rtf).

**Comment by 565ee** [comment]
how generate center view on my stereo pairs scene by baseline ?

**Comment by 565ee** [comment]
> Hi, are you trying to generate stereo pairs on your specific scene or are you using our dataset? In the latter case, you already have the center view for each rendered triplet. If you need more information, please refer to the documentation, which you can find at this [link](https://amsacta.unibo.it/id/eprint/7218/32/README_NeRF_stereo.rtf).

**Comment by fabiotosi92** [comment]
Once you have chosen a specific viewpoint, you can render the center image. From there, you can compute the pose by starting with an arbitrary baseline. This allows you to synthesize the left and right views. By doing so, you have your desired triplet.

**Comment by 565ee** [comment]
what code? what python packages?

**Comment by fabiotosi92** [comment]
This one:
https://github.com/NVlabs/instant-ngp

**Comment by fabiotosi92** [comment]
@565ee Pay attention to the fact that in our work, we do not generate a central view from a given stereo pair. Our approach involves generating stereo pairs from a NeRF model trained on multiple images captured by a single camera from different viewpoints of the scene.
