### ISSUE TITLE
Request tips for model training

### ISSUE THREAD

**Issue by chewry** [fabiotosi92/NeRF-Supervised-Deep-Stereo#14]
Thank you for sharing of your nice work!

Inspired by your work, I finetuned the model to apply this to another domain. Unfortunately, fine-tuning failed.  In order to check whether it is a domain problem, we fine-tuned the model on the provided NeRF-stereo triplet dataset, but failed as well. (Detection of texture rather than object boundary)

Because there is no code for the training, I used the same hyperparameter and augmentation procedures as RAFT-stereo, as written in your paper. Is there anything else to note for training? If you have any tips for training, please give me some advice.

**Comment by fabiotosi92** [comment]
Hi @chewry, could you please be more specific? What do you mean by fine-tuning failing? Does the network forget how to perform stereo matching or does it simply worsen the disparity estimates?

**Comment by chewry** [comment]
Yes. the network forget how to perform stereo matching. The finetuned model detects texture of the objects.
I use the same augmentation procedures as RAFT-stereo except _resize_sparse_flow_map_. 
(The sparse resizing makes the results worse. Textures regions are more emphasized.) 

Did you use the all augmentations in RAFT-stereo (color transform, erasing regions, resizing, horizontal flip, ...)?

**Comment by mattpoggi** [comment]
Hi,
Can you share an output from your finetuned model?

**Comment by Liyunfengabc** [comment]
Thank you for sharing of your nice work!
I want to follow your work, but the model trained by myself performance very bad, can you give me the trainning data augmentations code?
