### ISSUE TITLE
What should be paid attention to in video capture？

### ISSUE THREAD

**Issue by aiforworlds** [fabiotosi92/NeRF-Supervised-Deep-Stereo#15]
thank your share so perfect project，
I have a question about the uploaded video, what conditions must be met for the video, if I need to generate video data of portraits, how to shoot the video will be better，
What kind of video will cause failure？

**Comment by fabiotosi92** [comment]
Thank you for your interest in our project!

Regarding your question, we initially attempted to use videos captured from the scene. However, we noticed that this approach often led to motion blur effects in the images, which affected the quality of the generated data.

To address this issue and ensure better results, we decided to capture 100 individual photos for each scene. This allowed us to achieve sharper and more focused images, which in turn improved the overall quality of the generated data.
