### ISSUE TITLE
about the process of data production

### ISSUE THREAD

**Issue by aiforworlds** [fabiotosi92/NeRF-Supervised-Deep-Stereo#16]
Thank you for your great work
In the process of data production, how to use colmap? Does colmap use the original code? Is every frame of the video used?

**Comment by fabiotosi92** [comment]
I apologize for the delay in responding; I was on vacation for the past few days.

In our data production process, we utilized the **colmap2nerf.py** script from the Instant-NGP repository, which can be found at the following [link](https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py). This script allowed us to estimate poses for our scenes effectively.

Regarding the usage of frames, we indeed employed all frames acquired during the scene capture for training our model.
