### ISSUE TITLE
Question about the number of training samples

### ISSUE THREAD

**Issue by husheng12345** [fabiotosi92/NeRF-Supervised-Deep-Stereo#20]
Hello, I download the training set and get a total number of 79,584 triplets. However, as mentioned in Section 4.1 in your paper, the number should be 65,148. I wonder what is the reason for the difference in the numbers, thank you.
Here is the training file I used: [train.txt](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/files/12376273/train.txt)

**Comment by fabiotosi92** [comment]
Hi, this difference is due to the fact that we excluded from the training set some failure cases when synthesizing images from NeRF. You can find a comprehensive explanation in Section 5 - "Rendering Failure Cases" of the supplementary material.

**Comment by husheng12345** [comment]
I get it now. Could you please show me your code for filtering or offer the resulting training file.

**Comment by fabiotosi92** [comment]
The provided [training file](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/files/12376273/train.txt) already contains all the triplets from our dataset that have passed the filtering phase. For training, you can simply use that file.

**Comment by husheng12345** [comment]
Sorry, I get confused again. According to Section 5, there are 65,148 triplets out of 81,000 triplets after filtering. By contrast, my training file contains 79,584 triplets. I wonder which number is correct.

**Comment by fabiotosi92** [comment]
We have 270 scenes, each containing 100 images. This should theoretically yield a total of 270x100=27,000 triplets for a single baseline. Considering that we utilized 3 different baselines, we should have obtained 270x100x3 = 81,000 triplets. However, during the pose estimation process using COLMAP, not all of these images are employed. COLMAP, instead, strategically selects a subset of images to ensure a comprehensive view of the scene being reconstructed. Consequently, not all the 'transform.json' files generated using Instant-NGP contain 100 entries in each sequence. As a result, the total number of triplets consolidates to 79,584. Subsequently, our filtering mechanism eliminates triplets that fail to meet the criteria outlined in Section 5 - 'Rendering Failure Cases.' This process culminates in a final set of 65,148 triplets that are employed for training the stereo networks.

**Comment by husheng12345** [comment]
Thank you very much for explaining this to me. It seems that I have difficulties in implementing the filtering mechanism because it requires the AO map for each rendered image, while the dataset only contains AO maps for center images. So could you please post the training file of 65,148 triplets?

**Comment by fabiotosi92** [comment]
Wait, the link to the correct training file is https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/blob/main/filenames/trainingQ.txt. It contains 65,148 triplets. 

Could you please tell me where you found [this one](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/files/12376273/train.txt)?

**Comment by husheng12345** [comment]
That file is excatly what I what. Sorry I didn't notice it before. And [this file](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/files/12376273/train.txt) is generated by my own script, it's a stupid mistake of mine.
