### ISSUE TITLE
How to calculate AO?

### ISSUE THREAD

**Issue by Liyunfengabc** [fabiotosi92/NeRF-Supervised-Deep-Stereo#24]
Thanks for your great work, I would like to know how to calculate AO, can you provide the formula please? The formula provided in your paper is wrong. The confidence map obtained by the formula provided in the paper is almost all 1.

**Comment by fabiotosi92** [comment]
We have calculated the Ambient Occlusion (AO) using the  ([Instant-NGP framework](https://github.com/NVlabs/instant-ngp)) by configuring `testbed.render_mode = ngp.AO`. Furthermore, if you wish to utilize our dataset, please be informed that these AO maps are readily accessible.

**Comment by Liyunfengabc** [comment]
Thank you for your reply. I want to use the method you proposed in the paper to make datasets for other scenes. I use nerf studio to calculate AO. I use the formula you proposed in the paper to calculate AO, but the AO obtained is almost all 1. I want to know if there is something wrong with the formula in your paper.

**Comment by mattpoggi** [comment]
Hi,
yes, it seems there's a typo in the equation. According to https://github.com/NVlabs/instant-ngp/blob/master/src/testbed_nerf.cu, an extra alpha is missing

**Comment by Liyunfengabc** [comment]
Hi, Could you please provide me with the correct formula for calculating AO?

**Comment by Sparsh913** [comment]
Hi @Liyunfengabc 
Were you able to figure it out?
