### ISSUE TITLE
 I can't download the dataset.Is there a problem with the data source？

### ISSUE THREAD

**Issue by SKYMIRRORA** [fabiotosi92/NeRF-Supervised-Deep-Stereo#3]
When I'm halfway through the download, the download is interrupted. I've tried it a few times, and it's all like this. I'm guessing it seems like there's a problem with the data source.

**Comment by fabiotosi92** [comment]
Hi, could you kindly provide the link from which you're trying to download the ZIP file? This will allow me to investigate the issue and find a solution.

**Comment by SKYMIRRORA** [comment]
Thank you for your quick reply.Here are some links I've tried.[https://doc-04-78-docs.googleusercontent.com/docs/securesc/729dp6o8luf370dco9amlvqbrqr0hk96/8jq0cna66tqidt944ldvbmg2j2aemsth/1686561600000/14834649529279567867/11664283015214864622/1Z5TrZ8kIP3Ims5wiEhjNYs3pg0S6cl0g?e=download&ax=ADWCPKAEreNwGGqQzrr-oI6OlSbpIhghxmJxDwaERf7G_6Mg7gA7lFywemy_utGrWpkPqrng-iyQGxNp1UJC3fOpA40hxL8LqQOOHdidGjClbE4VHwr9_si9XzUjCDyEy2UQfxOW8iNEdwtkXgn2PzY5KlW_e9o5qJ0jzop6OPcWbSaGugUZ0LIUV01bdpVMHRAleWTC-LsGaxAOqfZtXwQJplRhr3_iZXvXKL2vomXjlfEzXJnjfCxpZGUnzQw1j1esdtMZjm6yq0NpY24PV6C7D6QctxszTddTbeNLGtjsz_2j0EpPFcvNI3aaXVa-VQ_zFF2iYGZPnVm0hAcp0WHd_TRs8W5DXkeV2b8wTwL0laOnUdPGiwWrTtM6dBFOyqCOq4TzDM6hTRM33-835gf1usUPB_yjDH3haDYqg29ghO8mY1qi-a7TSu9u4jaK3hRFYPOvvmXApHgcrbEVGiJvOdToWpvURf1BaYKqMFsStp-nYyt59DCdRRe2tcdqDNZREbYYlugX5HujRBgrOnFM8f8pM92wIxa86AaUQLIj3eyenvM5SjN7A_OEFcOazflGMjnS6ONGF7vOO-RMoPp3xAs0g-8dNeEp6xV-vCjvz_3h7BfuuONNuMhtPfmwB4-wQ23-U2H_hq83kHSZTPPp-W9PlfworQ8FoeyPj28Q4rJrwmvRIC-XY4GIUMPaVaRyHDGbrLaXPA0RB1JcGmfNS-aEmUGEhA0xZG9SQNiqI6J4sE-RXgRLctO3FmxnJ9Q95kqx_LYIoDtWnt8aO2A7DaRty9Oo8NydLpbYz05TnTyoscKYIccrIHoBX9B7BgPnoGCwwo5RvzvOu5pTCBw1FIcFfYf1y6FUS1Uuf2LXdqHR3TXRhf7eBPi-7vo6IuovIw&uuid=824494cb-d61a-477f-8dc4-48e79af76f33&authuser=0](url)[https://doc-0o-78-docs.googleusercontent.com/docs/securesc/729dp6o8luf370dco9amlvqbrqr0hk96/06i9lj7068i9pj98kjin8n0e5uhgih5d/1686561525000/14834649529279567867/11664283015214864622/1C-04OcWRM5GPOvMB7dpqIbzpiMcJqw80?e=download&ax=ADWCPKDG4UUAbfldyXyt4DE_yjJ0C7MXEV7NLTGd0kWIi1umSKlURoAtyg_PNHbVxixhZcv1jCVrj7gqAlcXqT9fWCzkeynvfPHglLE7pMyPtmY0xvIElZDt54HWeKeaLEEiwHNKLmCsNEoBznemj0px_ourGhK2d5gIfV_-iDt_tSBkmo9zxZCZuVvlPu_34GFuQGxJa1uV9WeTdztMyeWW8i7c0-wZGrz4rbMX_1G91D9iulm3qA4n2AAQUzKs8b0dYqFPHUF911LIRWGmGRf14P5T6AuOmv0oJ7-dMikrxpUSlNvTVTYzvDrq-IebqKUjRYHbqCCjOSYWdMLrCh5pMEmgW6pLQ5h5ZaKrXOjjvoqSQffmgexRjTa8tHtnj3o8XySbrbk0PKunusBiyGzb3x5C7dguDEu1O6XUMKdyQIE3MdKJqsUEFJee5LG_ie63Nx3T3dmQpottUifVuIjtuG5DakYhyq7rR2M2SPlFyDwCT5M8XIN3j45dHhn3cmtCnE7WzgCC9QSnNohUIh07Qt98cCCldftKGSq12a2LCC4kk4m1NjOZ21OYbwQ2RbYW6dGVpVPIBBzcKwlCiPWDG6F5111X7pQRAyJwwN8JPOY28vYZXlTQDEX9q6puAIU9mur-4j71bcb0RoWB5tpho0oQiFOR_JWafxqMV3-yNzwBbGsLxtyTEqAe4ra3c4ydpeBsejA_E-q5jmGikSQvuveMvtK_r09fDQQiqdNAIAPmktoKBzyeVjJF2-JIe_Q8PAX7_Y4G2N4d5S4cPA182OSnz6upUjpP7zyJjbtqAmvtSn1BXXBgDtoBpOWDHWyoFzZUL9ThBpGtqve8pcUex-9TbaJxDtjP2mee0jMF-bbsagSYMpcW01_qZqoHamxcGg&uuid=f7e61d3c-141b-48ab-b3b4-65c809039596&authuser=0&nonce=7j0rqq5msivn6&user=11664283015214864622&hash=8l634pcp9pk1qk3oan1i1jv44gfkgqmf
](url)

**Comment by SKYMIRRORA** [comment]
Thank you for your quick reply.Here are some links I've tried.
[https://doc-0o-78-docs.googleusercontent.com/docs/securesc/729dp6o8luf370dco9amlvqbrqr0hk96/06i9lj7068i9pj98kjin8n0e5uhgih5d/1686561525000/14834649529279567867/11664283015214864622/1C-04OcWRM5GPOvMB7dpqIbzpiMcJqw80?e=download&ax=ADWCPKDG4UUAbfldyXyt4DE_yjJ0C7MXEV7NLTGd0kWIi1umSKlURoAtyg_PNHbVxixhZcv1jCVrj7gqAlcXqT9fWCzkeynvfPHglLE7pMyPtmY0xvIElZDt54HWeKeaLEEiwHNKLmCsNEoBznemj0px_ourGhK2d5gIfV_-iDt_tSBkmo9zxZCZuVvlPu_34GFuQGxJa1uV9WeTdztMyeWW8i7c0-wZGrz4rbMX_1G91D9iulm3qA4n2AAQUzKs8b0dYqFPHUF911LIRWGmGRf14P5T6AuOmv0oJ7-dMikrxpUSlNvTVTYzvDrq-IebqKUjRYHbqCCjOSYWdMLrCh5pMEmgW6pLQ5h5ZaKrXOjjvoqSQffmgexRjTa8tHtnj3o8XySbrbk0PKunusBiyGzb3x5C7dguDEu1O6XUMKdyQIE3MdKJqsUEFJee5LG_ie63Nx3T3dmQpottUifVuIjtuG5DakYhyq7rR2M2SPlFyDwCT5M8XIN3j45dHhn3cmtCnE7WzgCC9QSnNohUIh07Qt98cCCldftKGSq12a2LCC4kk4m1NjOZ21OYbwQ2RbYW6dGVpVPIBBzcKwlCiPWDG6F5111X7pQRAyJwwN8JPOY28vYZXlTQDEX9q6puAIU9mur-4j71bcb0RoWB5tpho0oQiFOR_JWafxqMV3-yNzwBbGsLxtyTEqAe4ra3c4ydpeBsejA_E-q5jmGikSQvuveMvtK_r09fDQQiqdNAIAPmktoKBzyeVjJF2-JIe_Q8PAX7_Y4G2N4d5S4cPA182OSnz6upUjpP7zyJjbtqAmvtSn1BXXBgDtoBpOWDHWyoFzZUL9ThBpGtqve8pcUex-9TbaJxDtjP2mee0jMF-bbsagSYMpcW01_qZqoHamxcGg&uuid=f7e61d3c-141b-48ab-b3b4-65c809039596&authuser=0&nonce=7j0rqq5msivn6&user=11664283015214864622&hash=8l634pcp9pk1qk3oan1i1jv44gfkgqmf
](url)
[https://doc-04-78-docs.googleusercontent.com/docs/securesc/729dp6o8luf370dco9amlvqbrqr0hk96/8jq0cna66tqidt944ldvbmg2j2aemsth/1686561600000/14834649529279567867/11664283015214864622/1Z5TrZ8kIP3Ims5wiEhjNYs3pg0S6cl0g?e=download&ax=ADWCPKAEreNwGGqQzrr-oI6OlSbpIhghxmJxDwaERf7G_6Mg7gA7lFywemy_utGrWpkPqrng-iyQGxNp1UJC3fOpA40hxL8LqQOOHdidGjClbE4VHwr9_si9XzUjCDyEy2UQfxOW8iNEdwtkXgn2PzY5KlW_e9o5qJ0jzop6OPcWbSaGugUZ0LIUV01bdpVMHRAleWTC-LsGaxAOqfZtXwQJplRhr3_iZXvXKL2vomXjlfEzXJnjfCxpZGUnzQw1j1esdtMZjm6yq0NpY24PV6C7D6QctxszTddTbeNLGtjsz_2j0EpPFcvNI3aaXVa-VQ_zFF2iYGZPnVm0hAcp0WHd_TRs8W5DXkeV2b8wTwL0laOnUdPGiwWrTtM6dBFOyqCOq4TzDM6hTRM33-835gf1usUPB_yjDH3haDYqg29ghO8mY1qi-a7TSu9u4jaK3hRFYPOvvmXApHgcrbEVGiJvOdToWpvURf1BaYKqMFsStp-nYyt59DCdRRe2tcdqDNZREbYYlugX5HujRBgrOnFM8f8pM92wIxa86AaUQLIj3eyenvM5SjN7A_OEFcOazflGMjnS6ONGF7vOO-RMoPp3xAs0g-8dNeEp6xV-vCjvz_3h7BfuuONNuMhtPfmwB4-wQ23-U2H_hq83kHSZTPPp-W9PlfworQ8FoeyPj28Q4rJrwmvRIC-XY4GIUMPaVaRyHDGbrLaXPA0RB1JcGmfNS-aEmUGEhA0xZG9SQNiqI6J4sE-RXgRLctO3FmxnJ9Q95kqx_LYIoDtWnt8aO2A7DaRty9Oo8NydLpbYz05TnTyoscKYIccrIHoBX9B7BgPnoGCwwo5RvzvOu5pTCBw1FIcFfYf1y6FUS1Uuf2LXdqHR3TXRhf7eBPi-7vo6IuovIw&uuid=824494cb-d61a-477f-8dc4-48e79af76f33&authuser=0](url)

**Comment by fabiotosi92** [comment]
The link you should use for the download is this:

https://amsacta.unibo.it/id/eprint/7218/

From here, you should be able to download each zip file individually. Simply click on the "Download" button to initiate the download process.

**Comment by SKYMIRRORA** [comment]
Thanks, I'll try it out.
