### ISSUE TITLE
Can not download the dataset. 

### ISSUE THREAD

**Issue by mendoza-G** [fabiotosi92/NeRF-Supervised-Deep-Stereo#30]
Thanks for your wonderful job! But I can not download the dataset from the link https://amsacta.unibo.it/id/eprint/7218/

**Comment by mattpoggi** [comment]
Hi, 
what's the problem?

**Comment by mendoza-G** [comment]
Don't know how to download the dataset, when I click any of the links, this page shows with nothing be downloaded, what should I do? Thanks for your reply. 
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/81526517/a19c335e-2481-41d9-bb29-b3979c0dbd91)

**Comment by mattpoggi** [comment]
You clicked on the license file.... you need to click on "Download"

**Comment by mendoza-G** [comment]
sorry~ Thanks for your help.
