### ISSUE TITLE
[Positive Feedback]

### ISSUE THREAD

**Issue by CaptainEven** [fabiotosi92/NeRF-Supervised-Deep-Stereo#36]
Thanks for the great work and help! I have roughly succeeded run through the whole pipeline of your paper with custome dataset, as below picpure shows.
![0064](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/9303747/18ef398c-7141-47cc-b4a0-baf2c2f8cb2b)

**Comment by guwenxiang1** [comment]
I also tried to generate stereo matching using mip-nerf-360, but the results were not ideal. I mentioned this issue in another issue. Can you try to help me answer my question? Thank you very much. https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/issues/35#issue-1951104867

**Comment by guwenxiang1** [comment]
Sorry, I also used instant ngp for rendering, and there was no problem. It could be a problem with mip-nerf-360.

**Comment by Miaowei-HNU** [comment]
> Thanks for the great work and help! I have roughly succeeded run through the whole pipeline of your paper with custome dataset, as below picpure shows. ![0064](https://private-user-images.githubusercontent.com/9303747/276868735-18ef398c-7141-47cc-b4a0-baf2c2f8cb2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MTA5MjgsIm5iZiI6MTcwMjYxMDYyOCwicGF0aCI6Ii85MzAzNzQ3LzI3Njg2ODczNS0xOGVmMzk4Yy03MTQxLTQ3Y2MtYjRhMC1iYWYyYzJmOGNiMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDMyMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI4MWVjN2FiYjRlMWFjMDllYWMwOWQzOGU3MWY5NWIwYzRmMGVjOWI0NWY5YzFjOTg3OThiOTdlNTcwZjI3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0V2HC3Gq8kfGnwQMydeodTQKuLF05CNDPNO6qboGmpg)

Hi, do you know how to render depth with python in ngp  scripts/run.py? how to set the params or pass args to the render() function? the depth is used for stereo or needs to be scaled?
