### ISSUE TITLE
Gpu ram size and processing speed needed?

### ISSUE THREAD

**Issue by luuude** [fabiotosi92/NeRF-Supervised-Deep-Stereo#37]
I would like to test your wonderful paper with some scenes of my own and I wonder how much time and what gpu you trained on? You trained on .5 Mpix, did you try wirh higher resolutions also?

**Comment by fabiotosi92** [comment]
We trained our model using a single Nvidia 3090 GPU. Additionally, we conducted experiments with higher resolutions, as indicated in Table 3 of the paper. Training durations typically range from 2 to 3 days, depending on the stereo architectures employed and the hardware specifications.
