### ISSUE TITLE
Focal length of each scene.

### ISSUE THREAD

**Issue by XrKang** [fabiotosi92/NeRF-Supervised-Deep-Stereo#38]
Thanks for your great work.

Can you provide the focal length with a separate file?

Downloading the stereo dataset takes a long time, so downloading the RAW dataset will take the same long time, I just need the focus length to generate the corresponding depth.

This also will be helpful for others.

Thanks for your help!

**Comment by fabiotosi92** [comment]
Sorry, we don't plan to provide that separately.
