### ISSUE TITLE
model's predictions

### ISSUE THREAD

**Issue by Allessyer** [fabiotosi92/NeRF-Supervised-Deep-Stereo#4]
Thank you very much for the great work!
I just want to ask about the model's predictions. While running raft-stereo the resulting values are negative while the datasets' disparities are positive. Does that mean that we additionally need to preprocess input disparities as in raft-stereo (flow = np.stack([-disp, np.zeros_like(disp)], axis=-1)....)?

**Comment by fabiotosi92** [comment]
Thank you for bringing this to our attention. We appreciate your feedback. To address this issue, we have made an update to the original code in RAFT-Stereo.

Specifically, we have modified a line of code in the RAFT-Stereo implementation. Previously, the code at line 136 in the raft_stereo.py file (you can find it [here](https://github.com/princeton-vl/RAFT-Stereo/blob/main/core/raft_stereo.py)) read as follows: 

`flow_predictions.append(flow_up)`

We have made the following change:

`flow_predictions.append(-flow_up)`

By making this modification, we ensure that the model's predictions align with the positive values of the dataset's disparities.

Please let us know if you have any further questions or concerns.
