### ISSUE TITLE
About instant-ngp training

### ISSUE THREAD

**Issue by Miaowei-HNU** [fabiotosi92/NeRF-Supervised-Deep-Stereo#40]
I'm facing a problem, I'm using your v1 dataset (4640*2088) for instant-ngp training, but the rendering is not very well, do you mind providing your training parameters?
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/d99d2e49-a152-4842-ae27-0784ed1eaa9f)

**Comment by fabiotosi92** [comment]
I think it's more of an issue related to parameters used during rendering, not training (the scene seems to be fine from the screenshot). Try with these parameters:
 
--near_distance": -1.0,  
--exposure": 0.0
--screenshot_spp": 1
--marching_cubes_res": 256

**Comment by Miaowei-HNU** [comment]
@fabiotosi92 Thanks，I will try that, I have one more question, do I need to resize the image for training？

**Comment by fabiotosi92** [comment]
No, you don't. In our experiments, we used the original image resolution for training.

**Comment by Miaowei-HNU** [comment]
@fabiotosi92 I am rendering the transforms_left.json file which results in OUT of GPU memory, here is the script I am executing: 
command：scripts/run.py --load_snapshot  data/nerf/wall/60000.ingp --test_transforms data/nerf/wall/transforms_left.json
outputresult: failed: CUDA_ERROR_INVALID_VALUE
I didn't find the test-transformer section for adjusting the image resolution, do I need to do the transformation base_cam.json format? Is there a way to change the size of the rendered image?
