### ISSUE TITLE
Extracting stereo pairs from custom dataset. 

### ISSUE THREAD

**Issue by qureshinomaan** [fabiotosi92/NeRF-Supervised-Deep-Stereo#41]
Hi Authors!
Really great work!
I have a query regarding creation of the stereo pairs and disparity from custom dataset. I am using [nerfstudio](https://docs.nerf.studio) to create my nerfs. How can I now begin to extract the stereo pairs?

**Comment by fabiotosi92** [comment]
Hi, thank you so much for appreciating our work. Regarding your question, in our project, we didn't use nerfstudio but rather the original code from Instant-NGP. However, the process remains consistent: first, you train any NeRF model following nerfstudio's instructions. Then, for creating stereo pairs, you render two novel views, one from an arbitrary viewpoint and the other from its corresponding virtual stereo camera viewpoint. If it helps, you can use this [code](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/blob/main/code_snippets/generate_stereo_pair_matrix.py) to generate poses for stereo view pairs.

**Comment by qureshinomaan** [comment]
Hi @fabiotosi92! Thanks a lot for responding! We were able to extract similar dataset from nerfstudio using your script! 
I also wanted to say that this is perhaps the first algorithm that worked in our case (agriculture dataset). This is a neat idea!
