### ISSUE TITLE
The structure of the folders in Setup Instructions

### ISSUE THREAD

**Issue by Charlielyo** [fabiotosi92/NeRF-Supervised-Deep-Stereo#42]
Thank you for your contribution.
I have a question to ask you.
Can you give me the structure of the folders in Setup Instructions. This step is confusing and causes problems in operation.
Thank you again for your contribution and I look forward to your reply.

**Comment by fabiotosi92** [comment]
Hi, the structure stays identical to the current repository. You just need to create a folder named _models_. Inside _models_, create another folder called either _raft-stereo_ or _psmnet_. Then, copy the contents from the original repositories of the respective architectures into these folders. I hope this answers your question. Feel free to reach out if you need further clarification.

**Comment by Charlielyo** [comment]
Thanks for your answer. But I keep running into a problem. The error is reported as follows.
“Traceback (most recent call last):
  File "test.py", line 15, in <module>
    from models.psmnet import PSMNet
ModuleNotFoundError: No module named 'models'"
Is this a structural problem in the models folder? I'm confused, thanks for the answer. We look forward to hearing from you.

**Comment by Charlielyo** [comment]
Thank you very much for your letter and please forgive me for interrupting
again.
When I'm running the code, I keep running into an issue. The error is
reported as follows.
“Traceback (most recent call last):
   File "test.py", line 15, in <module>
     from models.psmnet import PSMNet
ModuleNotFoundError: No module named 'models'"
The error code part is as follows (demo.py and test.py):

from models.psmnet import PSMNet
from models.raft_stereo import RAFTStereo
import datasets

Is this a structural problem in the models folder? I'm confused, thanks for
the answer. We look forward to hearing from you.
[image: image.png]
[image: image.png]


Fabio Tosi ***@***.***> 于2023年12月28日周四 17:35写道：

**Comment by ZYX-lang-lang** [comment]
Hello, I get the same error as you. Have you found a solution yet?
