### ISSUE TITLE
About instant-ngp depth

### ISSUE THREAD

**Issue by Miaowei-HNU** [fabiotosi92/NeRF-Supervised-Deep-Stereo#43]
Hi，Can you provide me with the code snippet to capture the depth, I'm having trouble with  instant-ngp! help @fabiotosi92

**Comment by fabiotosi92** [comment]
Hi! In the original code of Instant-Ngp, you simply need to set `testbed.render_mode` to `ngp.Depth`.

**Comment by Miaowei-HNU** [comment]
> Hi! In the original code of Instant-Ngp, you simply need to set `testbed.render_mode` to `ngp.Depth`.

![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/1bd6d9aa-d67a-4f3b-9869-5870852ee1cb)
I did it in the same way, but I got an all-white image.

**Comment by fabiotosi92** [comment]
Are you saving it as `np.uint16`? I believe the issue might be related to how you are saving the image.

**Comment by Miaowei-HNU** [comment]
> Are you saving it as `np.uint16`? I believe the issue might be related to how you are saving the image.

I know the way to save the image so I saved the IMAGE（np float32 W*H*4） to see the exact value .
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/7aed3096-2d7a-4c76-9abf-a51a209eca3a)
I don't know how to calculate depth from these values

**Comment by fabiotosi92** [comment]
Try to visualize it using matplotlib. Let me know

**Comment by Miaowei-HNU** [comment]
> Try to visualize it using matplotlib. Let me know
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/861f2eed-0dcb-4f0f-af51-5cb88c76b629)

Here's my saved RGB image, the depth map is still all white, I'm curious how the depth is getting parsed out from 'image (H,W,4)'.

**Comment by fabiotosi92** [comment]
Consider to use the first channel -> `depth[:,:,0]`

**Comment by Miaowei-HNU** [comment]
> Consider to use the first channel -> `depth[:,:,0]`

![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/16c62a58-da67-4e6e-a63f-84d57632de83)
It still doesn't feel right. Do you remember how you handled it?

**Comment by fabiotosi92** [comment]
```
disparity = focal* args.baseline / image
disparity[np.isinf(disparity)] = 0
disparity[np.isnan(disparity)] = 0
plt.imsave(outname, disparity[:,:,0], cmap="magma")
```

**Comment by Miaowei-HNU** [comment]
> ```
> disparity = focal* args.baseline / image
> disparity[np.isinf(disparity)] = 0
> disparity[np.isnan(disparity)] = 0
> plt.imsave(outname, disparity[:,:,0], cmap="magma")
> ```
Oh, have you try to visualize the depth map, I'm using dataset0000, I'll try to visualize the disparity map.

**Comment by Miaowei-HNU** [comment]
> ```
> disparity = focal* args.baseline / image
> disparity[np.isinf(disparity)] = 0
> disparity[np.isnan(disparity)] = 0
> plt.imsave(outname, disparity[:,:,0], cmap="magma")
> ```

![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/100191082/2c6fd31f-cec6-4759-978f-e9fdeb7ab961)
I got the disparity map as you provided, but with the first dimension of the image (np) not representing the depth directly

**Comment by 3x5c2** [comment]
hi @Miaowei-HNU ,also i am troubled  in capture the depth can u show me the code
