### ISSUE TITLE
[About 3DGS Supervised Deep Stereo]

### ISSUE THREAD

**Issue by CaptainEven** [fabiotosi92/NeRF-Supervised-Deep-Stereo#47]
Hi, 3DGS has been prevalent nowadays， May i ask any palnnning to replace the NeRFs with 3DGS？

**Comment by fabiotosi92** [comment]
Hi! 

We have explored replacing NeRFs with 3D Gaussian Splatting but found that, despite 3DGS has faster inference times compared to NeRF variants, and sometimes better rendering quality, it still suffers from similar (or sometimes worse) geometric structure limitations compared to NeRF-based solutions, so depth/disparity supervision using 3DGS does not provide significant advantages at the moment. We will continue to monitor 3DGS developments for potential future incorporation.

**Comment by CaptainEven** [comment]
> Hi!
> 
> We have explored replacing NeRFs with 3D Gaussian Splatting but found that, despite 3DGS has higher inference times compared to NeRF variants, and sometimes better rendering quality, it still suffers from similar (or sometimes worse) geometric structure limitations compared to NeRF-based solutions, so depth/disparity supervision using 3DGS does not provide significant advantages at the moment. We will continue to monitor 3DGS developments for potential future incorporation.

Thanks for the exploration and explanation！
