### ISSUE TITLE
depth rendering

### ISSUE THREAD

**Issue by kiyojimini** [fabiotosi92/NeRF-Supervised-Deep-Stereo#5]
I use ngp.Depth to render depth and ngp.AO to render ao, but I dont know whether  this method can get absolute depth directly. do you know how to process the rendered depth to absolute depth? many thanks.
![image](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/55142103/ecf73a7e-9f9b-4b8e-923c-01b0f61dbcbd)

**Comment by xjcvip007** [comment]
I have the same and hope to get your answer~ @fabiotosi92

**Comment by fabiotosi92** [comment]
You don't have to determine the exact absolute depth for the specific goals. Instead, you only need to establish a virtual baseline to extract the corresponding disparity map, which represents the dense correspondence between a pair of stereo images. To calculate the disparity, you can use the formula f * b / depth, where f is the focal length and b is the virtual baseline.
