### ISSUE TITLE
 The formula for depth rendering

### ISSUE THREAD

**Issue by lsyl20** [fabiotosi92/NeRF-Supervised-Deep-Stereo#7]
Thank you for your wonderful work!
How to understand Formula 7 in the paper? 
Whether σ(i) in the formula should be changed to t(I). δi = t(i+1) - t(i).
![屏幕截图 2023-06-25 143125](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/56497902/8ed07da8-edca-440d-8ea3-b3e8c99c0fef)

t(i) represents the distance from the camera origin to the point.
Looking forward to your reply, thank you!

**Comment by fabiotosi92** [comment]
We appreciate you notifying us about this. 

Regarding Formula 7 in the paper, you are correct in noticing the typo. Unfortunately, there was an error in the formula as it was written. In fact, σ_i should indeed be replaced with t_i.

Thank you once again for bringing this to our attention!
