### ISSUE TITLE
Stereo image generation

### ISSUE THREAD

**Issue by PoyrazTahan** [fabiotosi92/NeRF-Supervised-Deep-Stereo#9]
Hey team, great work!

Will you share the pipeline for stereo image creation from single image? Let me know if it is uploaded and I am missing something

**Comment by fabiotosi92** [comment]
To clarify, could you please provide more details on what you mean by 'stereo image creation from a single image'? If I understand correctly, you are referring to generating the corresponding left and right views of a stereo triplet for each given view. In that case, starting from the **transform.json** file from Instant NGP, we recommend using the code snippet available at this [link](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/blob/main/code_snippets/generate_stereo_pair_matrix.py).

This code snippet should assist you in generating the stereo pair matrices for each view. Please let us know if you have any further questions or if there's anything else we can assist you with.
